export const products = [
  {
    id: '3bb8464e-e85f-11ec-8fea-0242ac120002',
    title: 'Yellow Pail',
    description: 'On-demand sand castle construction expertise.',
    url: '#',
    votes: 2,
    submitterAvatarUrl: 'images/avatars/daniel.jpg',
    productImageUrl: 'images/products/image-aqua.png',
  },
  {
    id: '47f524f4-e85f-11ec-8fea-0242ac120002',
    title: 'Supermajority: The Fantasy Congress League',
    description: 'Earn points when your favorite politicians pass legislation.',
    url: '#',
    votes: 5,
    submitterAvatarUrl: 'images/avatars/kristy.png',
    productImageUrl: 'images/products/image-rose.png',
  },
  {
    id: '54efe482-e85f-11ec-8fea-0242ac120002',
    title: 'Tinfoild: Tailored tinfoil hats',
    description: 'We already have your measurements and shipping address.',
    url: '#',
    votes: 1,
    submitterAvatarUrl: 'images/avatars/veronika.jpg',
    productImageUrl: 'images/products/image-steel.png',
  },
  {
    id: '64f172e2-e85f-11ec-8fea-0242ac120002',
    title: 'Haught or Naught',
    description: 'High-minded or absent-minded? You decide.',
    url: '#',
    votes: 5,
    submitterAvatarUrl: 'images/avatars/molly.png',
    productImageUrl: 'images/products/image-yellow.png',
  },
];

export const sortedProducts = [
  {
    id: '47f524f4-e85f-11ec-8fea-0242ac120002',
    title: 'Supermajority: The Fantasy Congress League',
    description: 'Earn points when your favorite politicians pass legislation.',
    url: '#',
    votes: 5,
    submitterAvatarUrl: 'images/avatars/kristy.png',
    productImageUrl: 'images/products/image-rose.png',
  },
  {
    id: '64f172e2-e85f-11ec-8fea-0242ac120002',
    title: 'Haught or Naught',
    description: 'High-minded or absent-minded? You decide.',
    url: '#',
    votes: 5,
    submitterAvatarUrl: 'images/avatars/molly.png',
    productImageUrl: 'images/products/image-yellow.png',
  },
  {
    id: '3bb8464e-e85f-11ec-8fea-0242ac120002',
    title: 'Yellow Pail',
    description: 'On-demand sand castle construction expertise.',
    url: '#',
    votes: 2,
    submitterAvatarUrl: 'images/avatars/daniel.jpg',
    productImageUrl: 'images/products/image-aqua.png',
  },
  {
    id: '54efe482-e85f-11ec-8fea-0242ac120002',
    title: 'Tinfoild: Tailored tinfoil hats',
    description: 'We already have your measurements and shipping address.',
    url: '#',
    votes: 1,
    submitterAvatarUrl: 'images/avatars/veronika.jpg',
    productImageUrl: 'images/products/image-steel.png',
  },
];
